title: Kevin Luo
logo: "/images/profilePicture.png"
description:
  I am a third year student pursuing a BS in Computer Science at UCSD.
  <br><br>
  Most interested in back-end development and working with API's, but I am also experienced with front-end development tools such as ReactJS, HTML, and CSS.
theme: jekyll-theme-minimal
