title: Kevin Luo
logo: "/images/profilePicture.png"
description:
  I am a third year student pursuing a BS in Computer Science at UCSD.
  <br><br>
  I am most interested and experienced in back-end development and working with API's, but I am learning front-end development tools such as React, HTML, and CSS.
theme: jekyll-theme-minimal
